services:
  redis:
    image: redis:7.4.0
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
    command: [ "redis-server", "--appendonly", "yes" ] # Redis에 데이터를 지속시키기 위한 설정

volumes:
  redis-data: