services:
  mariadb:
    image: mariadb:11.5.2
    restart: always
    volumes:
      - ./mariadb-data:/var/lib/mysql
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${FOORI_MYSQL_DATABASE}
      MYSQL_USER: ${FOORI_MYSQL_USER}
      MYSQL_PASSWORD: ${FOORI_MYSQL_PASSWORD}
    networks:
      - app-network

volumes:
  mariadb-data:

networks:
  app-network:
    external: true
